config/routes.rb
Sgg::Application.routes.draw do
match '/', :to => 'topics#index'
match '/new', :to => 'topics#new'
match '/edit', :to => 'topics#edit'
match '/admin', :to => 'topics#admin'

resources :topics

root :to => "topics#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  USER, PASSWORD = 'admin', 'reallystrongpassword'
 
  before_filter :authentication_check, :only => [:show,:delete, :edit]

  # GET /topics
  # GET /topics.xml


def home
   
end

  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.xml
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.xml
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.xml
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
  format.html { redirect_to(root_path,:notice => 'Topic was successfully created.') }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }

      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.xml
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to(@topic, :notice => 'Topic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.xml
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to(topics_url) }
      format.xml  { head :ok }
    end
  end

private
  def authentication_check
    authenticate_or_request_with_http_basic do |user, password|
      user == USER && password == PASSWORD

end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_header.html.erb
  <%= image_tag("http://www.goodhope.org.uk/images/heft.jpg", :alt => "Suggestions App", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", '/' %></li>
     
     
    </ul>
  </nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'bootstrap', :media => 'screen' %>
<%= stylesheet_link_tag 'custom',  :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestion Box App</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
       <%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>
      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
<div class="field">

  <%= f.label :description %><br />
<center><p>    <%= f.text_area :description, :cols => 100  %></p></center>
  </div>

  <div class="actions">
    <%= f.submit :submit %>
  </div>

<% end %>

app/views/topics/admin.html.erb
<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/home.html.erb
<p>
<% @topics.each do |topic| %>
  <tr>
  <p>  <td><%= topic.title %></td> </p>
    <td><%= link_to 'Show', topic %></td>
  <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
<%end%>
</p>

app/views/topics/index.html.erb
<center><h1>Suggestion Box
<p>
<img src="http://www.goodhope.org.uk/images/heft.jpg" alt="W3Schools.com" />
</p></hr> </center>
<br />
<center>
<p>Remember you can say what you like and ask whatever you want, but it must be constructive!
</p>
</center>
<p>


</p>
<center>

<%= link_to 'Suggest Something', new_topic_path %>


</center>

app/views/topics/new.html.erb
<center><h1>Submit a suggestion</h1></center>
<center>
<%= render 'form' %>
</center>
<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @topic.title %>
</p>

<p>
  <b>Content:</b>
  <%= @topic.description %>
</p>



<%= link_to 'Back', topics_path %>